language: go

sudo: required
dist: trusty

go:
 - 1.6

install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get update -qq
  - sudo apt-get install -qq upx
  - sudo ./.travis-install-rkt.sh

script:
  - ./build.sh
  - sudo PATH=${GOPATH}/bin:$PATH ./tests.sh
  - sudo PATH=${GOPATH}/bin:$PATH ./examples/build.sh
